name: Build and Test watchOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Build using the specified scheme
    - name: Build watchOS App
      run: xcodebuild -project quick-timer.xcodeproj
