name: Build watchOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Build all targets
    - name: Build all targets
      run: xcodebuild -project QuickTimer.xcodeproj \
                      -alltargets \
                      -sdk watchsimulator \
                      -destination 'platform=watchOS Simulator,name=Apple Watch Series 7,OS=latest' \
                      clean build
